export const tarotSpreads = [
    {
        name: "One Card",
        description: "Beginner",
        image: "/images/spreads/one-card.png",
        cardMeaning: ["1. Response"],
        slug: "one-card",
        plan: "Free",
    },
    {
        name: "Three Cards",
        image: "/images/spreads/three-card.png",
        description: "Beginner",
        cardMeaning: ["1. Past", "2. Present", "3. Future"],
        slug: "three-cards",
        plan: "Free",
    },
    {
        name: "Five-Card",
        image: "/images/spreads/five-card.png",
        description: "Intermediate",
        cardMeaning: [
            "1. Present",
            "2. Influences",
            "3. Challenges",
            "4. Final Outcome",
            "5. Theme",
        ],
        slug: "five-card",
        plan: "Pro",
    },
    {
        name: "HorseShoe",
        image: "/images/spreads/horseshoe.png",
        description: "Intermediate",
        cardMeaning: [
            "1. Past Influences",
            "2. Present Issue",
            "3. Future development",
            "4. Advice for the querent",
            "5. How people around the issue affect the querent's decision",
            "6. Obstacles or hidden influences",
            "7. Optimal action for resolution",
        ],
        slug: "horseshoe",
        plan: "Pro",
    },
    {
        name: "Celtic Cross",
        image: "/images/spreads/celtic-cross.png",
        description: "Intermediate",
        cardMeaning: [
            "1. Present",
            "2. Challenge",
            "3. Subconscious",
            "4. Past",
            "5. Mind",
            "6. Future",
            "7. Internal Influences",
            "8. External Influences",
            "9. Hopes and/or Fears",
            "10. Outcome",
        ],
        slug: "celtic-cross",
        plan: "Pro",
    },
    {
        name: "Astrological",
        image: "/images/spreads/astrological.png",
        description: "Advanced",
        cardMeaning: [
            "1. How do you define yourself?",
            "2. What guides your dreams?",
            "3. How do you incorporate what you love into your decisions?",
            "4. How do you stay focused?",
            "5. How do you confront conflict?",
            "6. How do you regulate your emotions?",
            "7. What must you do to be fair to yourself and those around you?",
            "8. What do you need to release?",
            "9. What requires more balance?",
            "10. Temptations",
            "11. What is your heart's desire?",
            "12. What aspects of your shadow should be brought to light?",
        ],
        slug: "astrological",
        plan: "Pro",
    },
];
